[tools]
node = '22'
bun = 'latest'
deno = 'latest'

[tasks.projects-sync]
run= """
deno run -A ./.eng/main.ts projects:sync
"""

[tasks.projects-list]
run= """
deno run -A ./.eng/main.ts projects:list
"""